### ISSUE TITLE
Backend framework

### ISSUE THREAD

**Issue by wrutkowski** [monitool/monitool-backend#1]
Since we decided to work with Node.js I suggest trying LoopBack Framework which seems to fit our needs and introduces a bunch of cool features out of the box. More on the website:

http://loopback.io

@monitool/owners What do you think?

**Comment by glowacki-bg** [comment]
As it's my first project with node.js i can't say much, but on first sight it looks nice

**Comment by DamianChodorek** [comment]
I have a little experience with node.js. I will gladly learn something new.

**Comment by akaluzinski** [comment]
I checked examples of this LoopBack and it looks nice. I'll start coding DB prototype tomorrow.

**Comment by PiotrGlab** [comment]
@akaluzinski  could you briefly describe LoopBack in Wiki? I mean, pros and cons and why this is the most suitable framework, when it comes to our project.

**Comment by akaluzinski** [comment]
@PiotrGlab Sure. I could describe LoopBack in Wiki, but I have never used it before. At first I'd like to write some code and check out if this is the best choice.

**Comment by PiotrGlab** [comment]
Ok, that is not a problem. When you will decide on sth else, please notice in Wiki that you have tried to use LoopBack but from some reasons you resign from that solution.

**Comment by DamianChodorek** [comment]
@wrutkowski tell me please, how will we handle access permissions? I mean, can anyone insert new sensors and data? Shouldn't we implement some users authentication?

Or do we assume that our system will be working only in closed environment?

@akaluzinski I think that loopback framework is great choice because it will create restful CRUD API for us. So we will have very little work to do ;) Don't you agree?

**Comment by wrutkowski** [comment]
@DamianChodorek It will work on intranet - closed environment as per specs, so no authentication both on GUI and Sensor's side.

**Comment by PiotrGlab** [comment]
When it comes to representing entities tools below migdy be useful:
- HAL
  http://stateless.co/hal_specification.html
- Collection+JSON
  http://amundsen.com/media-types/collection/
- JSON API
  http://jsonapi.org/
- Siren
  https://github.com/kevinswiber/siren

Or does the LoopBack do all the work?

**Comment by maniolek** [comment]
Guys, it seems that authentication is necessary for API. 

"6. Pomiar złożony można usuwać. 
7. Usunąć pomiar złożony może tylko ten użytkownik, który go stworzył. Oznacza to, że w systemie musi istnieć mechanizm uwierzytelniania i autoryzacji. "
