### ISSUE TITLE
Getting sensor's data 

### ISSUE THREAD

**Issue by brdeju** [monitool/monitool-backend#2]
Two problems:
1) How can I get data in date range? 
Eg. sensor's data from 2015-03-28 14:20:00 to 2015-03-28 15:00:00? 
In mongo it is: "date":{"and":[{"gt":"2015-03-28T13:20:00.000Z"},{"lt":"2015-03-28T13:51:00.000Z"}]} but in our's API it's not working (throw "Invalid date: [object Object]")
If there's no way to do this yet, you must add such possibility.
By the way, isn't it better to store date as timestamp not datetime?

2) In getting data by sensorId, there's should be possibility to get data for more then one sonsor (mongo query: {"sensorId":{"in":['id1","id2"]}}).
When user type in searching box name of sensor eg. "172.20.254" it should give data for each sensor with this string in name (I can get id of each of them, so it can be searched by array of id)

**Comment by DamianChodorek** [comment]
@brdeju read
https://github.com/monitool/monitool-backend/blob/master/HOW_TO_USE_IT.pdf
and
http://docs.strongloop.com/display/public/LB/Where+filter
you will find there how to do API queries. For example answers to your questions look like this:
1. {"where":{"and":[{"date":{"gt":"2015-03-28T13:10:33.970Z"}},{"date":{"lt":"2015-03-28T13:17:35.379Z"}}]}}

in url: ?filter={"where":{"and":[{"date":{"gt":"2015-03-28T13:10:33.970Z"}},{"date":{"lt":"2015-03-28T13:17:35.379Z"}}]}}&access_token=...
1. {"where":{"or":[{"sensorId":"5516a9b1a7a2230300824d5a"}, {"sensorId":"5516a9b1a7a2230300824d5a"}]}}

in url: ?filter={"where":{"or":[{"sensorId":"5516a9b1a7a2230300824d5a"}, {"sensorId":"5516a9b1a7a2230300824d5a"}]}}&access_token=...

@wrutkowski said that JSON is by definition human readable, so it's more proffessionall to leave datetime format.

**Comment by brdeju** [comment]
In how_to_use_it there's nothing about and / or query. 
Thanks for second link and answer.
