### ISSUE TITLE
The new version of the API.

### ISSUE THREAD

**Issue by DamianChodorek** [monitool/monitool-backend#4]
So today we've spoken with our supervisor. We need to change a few things. The officjal e-mail is:
"Zasób /sensors
- Skoro reprezentuje on hosty, to trzeba go po prostu nazwać /hosts,
  inaczej nazwa jest zupełnie nieadekwatna (myląca). Sensor jest
  szczegółem implementacji systemu monitorującego. W szczególności
  jednego hosta może monitorować wiele sensorów.
  [Poniżej już piszę /hosts zamiast /sensors]
- Powinny być porządne zasoby /hosts/{id}, tak żeby można było np.
  pobrać pomiary dla konkretnego hosta przez GET /hosts/{id}/data,
  zamiast filtrować po sensor_id na jednym globalnym zasobie /data.
- Nadal nie wiem jak się pobiera ostatnie kilka wartości konkretnego
  pomiaru. Naturalne byłoby np.:
  GET /hosts/{id}/data/cpuLoad"

and

"- Pomiar złozony -- poza tworzeniem i usuwaniem -- ma być obsługiwany
dokładnie tak samo jak prosty! Tzn. wartości nie mogą być pobierane
przez specjalny zasób /complexStat. Po prostu jest on widoczny jako
jeden z dostępnych pomiarów dla hosta. Żeby to było możliwe przy
tworzeniu wystarczy nadać nowemu pomiarowi nazwę (np. "avgCpuLoad10"
-- musi być unikalna dla danego hosta)."

So conclusions are:
1. instead of "sensor" we should have "host". To get data for host we should use /host/{id}/data and /host/{id}/data/cpuLoad. The assumption is that only one sensor can send data for one host and no more.
2. complexStat needs to be moved to /data and response format should look like /data format.

I will work on this in the next few days. If someone wants to do it please inform - what do you want to do :)

If any questions, please ask.

**Comment by DamianChodorek** [comment]
I get this error:
"Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete](net.js:983:19)"

I think it's a problem with connecting to db. With local db everything works fine. @akaluzinski could you check db? Please clean whole db also.

**Comment by DamianChodorek** [comment]
Nevermind I fixed bug. But please @akaluzinski clean db. Old data format is outdated.

**Comment by KaBogdal** [comment]
@DamianChodorek Done. I've totally cleaned up db.

**Comment by akaluzinski** [comment]
@DamianChodorek Done. I have cleaned up db.

**Comment by glowacki-bg** [comment]
I am trying to adjust autoclient to new API and I have problem with getting filtered data. I changed old filtering by sensorId to hosts/{sensorId}/data and if I want to order it by date and get newest one e.g. http://monitool.herokuapp.com/api/hosts/55414b86e99119030022621b/data?filter[order]=date%20DESC&filter[limit]=1&access_token=KBBHRLKAMhdqIxI4dAg1qYc7Cj034xtK1s6yIVSnH9i6ndVV6Wel7icwwoKyq3bA
it gives me error :
`{"error":{"name":"SyntaxError","status":500,"message":"Unexpected token o","stack":"SyntaxError: Unexpected token o\n    at Object.parse (native)\n    at Function.Host.getData (/app/common/models/host.js:22:16)\n    at SharedMethod.invoke (/app/node_modules/loopback/node_modules/strong-remoting/lib/shared-method.js:198:25)\n    at HttpContext.invoke (/app/node_modules/loopback/node_modules/strong-remoting/lib/http-context.js:335:12)\n    at /app/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:595:9\n    at execStack (/app/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:448:7)\n    at /app/node_modules/loopback/lib/application.js:329:13\n    at /app/node_modules/loopback/lib/model.js:311:7\n    at /app/node_modules/loopback/common/models/acl.js:465:23\n    at /app/node_modules/loopback/node_modules/async/lib/async.js:254:17"}}`
anybody knows whats going on?

**Comment by DamianChodorek** [comment]
Server crashed. I'll deal with this tomorrow.

**Comment by DamianChodorek** [comment]
Ok, bugs are fixed but please use ONLY Json format for queries:
http://monitool.herokuapp.com/api/hosts/554155a8e9911903002262fa/data?filter={"order":"date DESC","limit":1}&access_token=KBBHRLKAMhdqIxI4dAg1qYc7Cj034xtK1s6yIVSnH9i6ndVV6Wel7icwwoKyq3bA

**Comment by glowacki-bg** [comment]
Unfortunately, okhttp library used for comunication via http doesn't cope with some characters like '{' or '}'. Is there any chance to use version with [] brackets?

**Comment by glowacki-bg** [comment]
I tried to change http client to Apache HTTPClient, but got same exception. Unfortunately it is core Java problem and I'm afraid that "json format" for url cannot be used

**Comment by DamianChodorek** [comment]
Ok I did some changes. Both brackets and Json notations should work now.

**Comment by glowacki-bg** [comment]
Thanks It's working now. I would be grateful if sb could clean a bit up the database, cause since I implemented dealing with multiple monitors performance is weak point of my app.

**Comment by DamianChodorek** [comment]
@akaluzinski could you clean DB please? :)

**Comment by akaluzinski** [comment]
@DamianChodorek Ok. It's cleaned now.
