### ISSUE TITLE
Current server time

### ISSUE THREAD

**Issue by glowacki-bg** [monitool/monitool-backend#5]
Can Monitor give its current time via rest? It is needed for filtering sensors which stopped measurements and since heroku server time vary from my local time it's impossible.

**Comment by DamianChodorek** [comment]
If you go to http://monitool.herokuapp.com/ you will get Json obj like this:
{"started":"2015-05-07T06:57:49.814Z","uptime":7151.88}
"started" is server start time and "uptime" is how long it works in seconds. If you you add two values you will get current time.

In JS it would look like:
var currentServerTime=new Date( new Date(started).getTime() + uptime*1000);
